version: '2'

services:
  apirunner:
    image: lykkedev/lykke-ethereum-indexer-api:${tag}
    ports:
     - "${Port}:5000"
    environment:
     - ConnectionStrings__ConnectionString=${SettingsConnString}